apiVersion: batch/v1
kind: Job
metadata:
  name: mongodb-init-replica
spec:
  template:
    spec:
      containers:
      - name: mongodb-init-replica
        resources: {}
        image: mongoImage
        command: ["mongosh", "--host", "mongodb-service", "/init-mongo.js"]
        volumeMounts:
        - name: init-scripts
          mountPath: /init-mongo.js
          subPath: init-mongo.js
      restartPolicy: Never
      volumes:
      - name: init-scripts
        configMap:
          defaultMode: 420
          name: mongodb-init-scripts