### language filters
python:
  - 'apps/python/**'
  - 'packages/python/**'

### application filters
evaluator:
  - 'apps/python/evaluator/**'
manager:
  - 'apps/python/manager/**'
sampler:
  - 'apps/python/sampler/**'
sidecar:
  - 'apps/python/sidecar/**'