apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-admintools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal-admintools
  template:
    metadata:
      labels:
        app: temporal-admintools
    spec:
      containers:
        - name: temporal-admintools
          resources: {}
          image: temporalToolsImage
          env:
            - name: TEMPORAL_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: temporal-secret
                  key: TEMPORAL_ADDRESS
            - name: TEMPORAL_CLI_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: temporal-secret
                  key: TEMPORAL_ADDRESS
            - name: TEMPORAL_CLI_NAMESPACE
              valueFrom:
                secretKeyRef:
                  name: temporal-secret
                  key: TEMPORAL_ADDRESS

