services:
  sampler-worker:
    build:
      context: ../../
      dockerfile: apps/python/sampler/Dockerfile
    image: pocket_sampler:dev
    container_name: sampler
    environment:
      CONFIG_PATH: /home/app/configs/config.json
      OPENAI_API_KEY: EMPTY
    volumes:
      - $SAMPLER_CONFIG_FILE:/home/app/configs/config.json
    networks:
     - postgresql
     - temporal
     - mongodb
     - llm

networks:
  temporal:
    name: temporal
    external: true
  postgresql:
    name: postgresql
    external: true
  mongodb:
    name: mongodb
    external: true
  llm:
    name: llm
    external: true