kind: Secret
apiVersion: v1
metadata:
  name: requester-config
type: Opaque
stringData:
  config.json: |
    {
      "mongodb_uri": "mongodb://<MONGO-HOST>:27017/pocket-ml-testbench",
      "apps": [
        "<MORSE-APP-PRIVATE-KEY>"
      ],
      "rpc": {
        "urls": [
          "http://<MORSE-RPC-NODE-URL>:9081"
        ],
        "retries": 1,
        "min_backoff": 10,
        "max_backoff": 60,
        "req_per_sec": 3,
        "session_tolerance": 1
      },
      "relay": {
        "time_between_relays" : 3,
        "time_dispersion" : 0.25
      },
      "log_level": "info",
      "temporal": {
        "host": "temporal",
        "port": 7233,
        "namespace": "pocket-ml-testbench",
        "task_queue": "requester",
        "worker": {
          "identity": "requester",
          "enable_logging_in_replay": false,
          "max_concurrent_activity_task_pollers": 2500,
          "deadlock_detection_timeout": 120,
          "worker_activities_per_second": 500
        },
        "evaluator": {
          "workflow_name": "Evaluator",
          "task_queue": "evaluator"
        }
      },
      "external_suppliers" : {
        "external_some_name" : {
          "endpoint" : "https://some.endpoint", 
          "headers" : {
            "authorization" : "some string",
            "random" : "header data"
          }
        }
      }
    }