apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  labels:
    app: pgadmin
stringData:
  PGADMIN_DEFAULT_EMAIL: it@pnyxai.com
  PGADMIN_DEFAULT_PASSWORD: Q4c1Zc1B9nq8lOiuZHUI5dMyShw1QFE7JqZ5UBeuJhRWJZMySy
