kind: Secret
apiVersion: v1
metadata:
  name: manager-config
type: Opaque
stringData:
  config.json: |
    {
      "mongodb_uri": "mongodb://<MONGO-HOST>:27017/pocket-ml-testbench",
      "apps": ["<app addresss>","<app addresss>","<app addresss>","<app addresss>"],
      "pocket_rpc_url": "http://<host>:<port>",
      "pocket_grpc_config": {
          "host_port": "<host>:<port>",
          "insecure": true
        },
      "pocket_blocks_per_session" : 10,
      "log_level": "info",
      "develop": {
        "do_not_remove_tasks_from_db" : false
      },
      "temporal": {
        "host": "<TEMPORAL-HOST>",
        "port": 7233,
        "namespace": "pocket-ml-testbench",
        "task_queue": "manager",
        "worker": {
          "identity": "manager",
          "enable_logging_in_replay": false,
          "max_concurrent_activity_task_pollers": 80,
          "max_concurrent_workflow_task_pollers": 20,
          "deadlock_detection_timeout": 240
        },
        "sampler": {
          "workflow_name": "Sampler",
          "task_queue": "sampler"
        }
      },
      "frameworks": {
        "lmeh" : {
          "task_types": {"any" : "numerical"},
          "task_dependency": {"any" : ["signatures:tokenizer:ok", "signatures:config:ok"]},
          "schedule_limits": {"any" : "none:none"},
          "trigger_minimum": {"any" : "0"}
        },
        "helm" : {
          "task_types": {"any" : "numerical"},
          "task_dependency": {"any" : ["signatures:tokenizer:ok", "signatures:config:ok"]},
          "schedule_limits": {"any" : "none:none"},
          "trigger_minimum": {"any" : "0"}
        },
        "signatures" : {
          "task_types": {"any" : "signature"},
          "task_dependency": {"any" : ["none:none:none"]},
          "schedule_limits": {"any" : "1:session"},
          "trigger_minimum": {"tokenizer" : "1", "config" : "1"}
        }
      }
    }