kind: Secret
apiVersion: v1
metadata:
  name: summarizer-config
type: Opaque
stringData:
  config.json: |
    {
      "postgres_uri": "postgresql://<USER>:<PASS>@<HOST>:5432/pocket-ml-testbench",
      "mongodb_uri": "mongodb://mongodb-service:27017/pocket-ml-testbench",
      "temporal": {
        "host": "<HOST>",
        "port": 7233,
        "namespace": "pocket-ml-testbench",
        "task_queue": "summarize",
        "max_workers": 100,
        "max_concurrent_activities": 5,
        "max_concurrent_workflow_tasks": 5,
        "max_concurrent_workflow_task_polls": 5,
        "max_concurrent_activity_task_polls": 20
      },
      "log_level": "DEBUG",
      "taxonomies_path": "/home/app/code/taxonomies"
    }