kind: Secret
apiVersion: v1
metadata:
  name: evaluator-config
type: Opaque
stringData:
  config.json: |
    {
      "log_level": "WARN",
      "postgres_uri": "postgresql://<USER>:<PASS>@<POSTGRESQL-HOST>:5432/pocket-ml-testbench",
      "mongodb_uri": "mongodb://<MONGO-HOST>:27017/pocket-ml-testbench",
      "temporal": {
        "host": "<TEMPORAL-HOST>",
        "port": 7233,
        "namespace": "pocket-ml-testbench",
        "task_queue": "evaluator",
        "max_workers": 100,
        "max_concurrent_activities": 5,
        "max_concurrent_workflow_tasks": 5,
        "max_concurrent_workflow_task_polls": 5,
        "max_concurrent_activity_task_polls": 20,
        "manager-result-analyzer": {
          "workflow_name": "Manager-ResultAnalyzer",
          "task_queue": "manager"
        }
      },
      "include_path": "/home/app/code/packages/python/lmeh/custom_tasks"
    }
