apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampler
  labels:
    app: sampler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sampler
  template:
    metadata:
      labels:
        app: sampler
    spec:
      volumes:
        - name: configuration-files
          secret:
            secretName: sampler-config
      containers:
        - image: pocket_ml_testbench_sampler:dev
          name: sampler
          env:
            - name: CONFIG_PATH
              value: "/home/app/configs/config.json"
            - name: TQDM_DISABLE
              value: "True"
            - name: HF_DATASETS_DISABLE_PROGRESS_BARS
              value: "True"
            - name: OPENAI_API_KEY
              valueFrom:
                  secretKeyRef:
                    name: testbench-secret
                    key: OPENAI_API_KEY
            - name: HF_DATASETS_TRUST_REMOTE_CODE
              valueFrom:
                  secretKeyRef:
                    name: testbench-secret
                    key: HF_DATASETS_TRUST_REMOTE_CODE
            - name: DATASETS_TRUST_REMOTE_CODE
              valueFrom:
                  secretKeyRef:
                    name: testbench-secret
                    key: DATASETS_TRUST_REMOTE_CODE
            - name: EVALUATE_VERBOSITY
              valueFrom:
                  secretKeyRef:
                    name: testbench-secret
                    key: EVALUATE_VERBOSITY
            - name: DATASETS_VERBOSITY
              valueFrom:
                  secretKeyRef:
                    name: testbench-secret
                    key: DATASETS_VERBOSITY
            - name: AVERT_MODEL_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: testbench-config
                  key: avert_model_endpoint
            - name: AVERT_ENDPOINT_TYPE
              valueFrom:
                configMapKeyRef:
                  name: testbench-config
                  key: avert_endpoint_type
            - name: AVERT_MODEL_NAME
              valueFrom:
                configMapKeyRef:
                  name: testbench-config
                  key:  avert_model_name
          volumeMounts:
            - mountPath: /home/app/configs/
              name: configuration-files
              readOnly: true
          resources: {}