x-base: &base
  restart: unless-stopped
  extra_hosts:
    # this allows containers to call a port on the docker host machine
    # instead of localhost (because that will be container) use host.docker.internal
    # to resolve the docker host IP dynamically
    host.docker.internal: host-gateway
  networks:
    - morse-localnet
    - llm-engine-net
  logging:
    options:
      mode: non-blocking
      max-size: "10m"
      max-file: "3"

x-base-pocket-core: &base-pocket-core
  <<: *base
  image: poktscan/pocket-core:${POCKET_GEO_MESH_VERSION}
  command: [ "pocket", "start", "--datadir=/home/app/.pocket/", "--keybase=false", "--forceSetValidators" ]
  healthcheck:
    interval: 30s
    timeout: 1s
    retries: 10
  deploy:
    resources:
      limits:
        cpus: "2"
        memory: 3G

services:
  lean1:
    <<: *base-pocket-core
    container_name: lean1
    healthcheck:
      test: [ "CMD-SHELL", "wget --server-response --spider http://lean1.dev:8071/v1/health || exit 1" ]
    ports:
      - "8071:8071" # pokt rpc
      - "8073:8073" # prometheus
      - "26646:26646/tcp" # tendermint peer
      - "26646:26646/udp" # tendermint peer
      - "26647:26647" # tendermint rpc
    expose:
      - "26646"
    volumes:
      # Data
      - lean1:/home/app/.pocket
      
      # Exclusive main files
      - ./lean1/config.json:/home/app/.pocket/config/config.json
      - ./lean1/lean_nodes_keys.json:/home/app/.pocket/lean_nodes_keys.json
      
      # Common nodes files
      - ./config/genesis.json:/home/app/.pocket/config/genesis.json
      - ./config/chains.json:/home/app/.pocket/config/chains.json
      - ./config/auth.json:/home/app/.pocket/config/auth.json
    hostname: lean1.dev
    networks:
      morse-localnet:
        aliases:
          - lean1.dev
  
  lean2:
    <<: *base-pocket-core
    container_name: lean2
    healthcheck:
      test: [ "CMD-SHELL", "wget --server-response --spider http://lean2.dev:8081/v1/health || exit 1" ]
    ports:
      - "8081:8081" # pokt rpc
      - "8083:8083" # prometheus
      - "26656:26656/tcp" # tendermint peer
      - "26656:26656/udp" # tendermint peer
      - "26657:26657" # tendermint rpc
    expose:
      - "26656"
    volumes:
      # Data
      - lean2:/home/app/.pocket
      
      # Exclusive main files
      - ./lean2/config.json:/home/app/.pocket/config/config.json
      - ./lean2/lean_nodes_keys.json:/home/app/.pocket/lean_nodes_keys.json
      
      # Common nodes files
      - ./config/genesis.json:/home/app/.pocket/config/genesis.json
      - ./config/chains.json:/home/app/.pocket/config/chains.json
      - ./config/auth.json:/home/app/.pocket/config/auth.json
    hostname: lean2.dev
    networks:
      morse-localnet:
        aliases:
          - lean2.dev
  
  lean3:
    <<: *base-pocket-core
    container_name: lean3
    healthcheck:
      test: [ "CMD-SHELL", "wget --server-response --spider http://lean3.dev:8091/v1/health || exit 1" ]
    ports:
      - "8091:8091" # pokt rpc
      - "8093:8093" # prometheus
      - "26666:26666/tcp" # tendermint peer
      - "26666:26666/udp" # tendermint peer
      - "26667:26667" # tendermint rpc
    expose:
      - "26666"
    volumes:
      # Data
      - lean3:/home/app/.pocket
      
      # Exclusive main files
      - ./lean3/config.json:/home/app/.pocket/config/config.json
      - ./lean3/lean_nodes_keys.json:/home/app/.pocket/lean_nodes_keys.json
      
      # Common nodes files
      - ./config/genesis.json:/home/app/.pocket/config/genesis.json
      - ./config/chains.json:/home/app/.pocket/config/chains.json
      - ./config/auth.json:/home/app/.pocket/config/auth.json
    hostname: lean3.dev
    networks:
      morse-localnet:
        aliases:
          - lean3.dev
  
  mesh:
    <<: *base-pocket-core
    container_name: mesh
    command: [ "pocket", "start-mesh", "--datadir=/home/app/.pocket/" ]
    healthcheck:
      test: [ "CMD-SHELL", "wget --server-response --spider http://mesh.dev:9081/v1/health || exit 1" ]
    ports:
      - "9081:9081" # pokt rpc
#      - "9084:9084" # prometheus
    volumes:
      # Data
      - mesh:/home/app/.pocket
      # Exclusive main files
      - ./mesh/config.json:/home/app/.pocket/config/config.json
      - ./mesh/keys.json:/home/app/.pocket/key/keys.json
      # Common nodes files
      - ./config/auth.json:/home/app/.pocket/key/auth.json
      - ./config/chains.json:/home/app/.pocket/chains/chains.json
    hostname: mesh.dev
    networks:
      morse-localnet:
        aliases:
          - mesh.dev
    depends_on:
      lean1:
        condition: service_healthy
      lean2:
        condition: service_healthy
      lean3:
        condition: service_healthy
  

networks:
  morse-localnet:
    name: morse-localnet
    driver: bridge
  llm-engine-net:
    name: llm-engine-net
    external: true

volumes:
  lean1:
  lean2:
  lean3:
  mesh: