services:
  manager:
    image: registry.digitalocean.com/poktscan/pocket_ml_testbench_manager:dev
    pull_policy: always
    container_name: manager
    environment:
      CONFIG_PATH: /home/app/configs/config.json
    extra_hosts:
      host.docker.internal: host-gateway
    volumes:
      - $MANAGER_CONFIG_FILE:/home/app/configs/config.json
    networks:
      - testbench
      #- temporal
      #- mongodb
      - morse-localnet

  sampler:
    image: registry.digitalocean.com/poktscan/pocket_ml_testbench_sampler:dev
    pull_policy: always
    environment:
      CONFIG_PATH: /home/app/configs/config.json
      OPENAI_API_KEY: EMPTY
      HF_DATASETS_TRUST_REMOTE_CODE: "True"
      DATASETS_TRUST_REMOTE_CODE: "True"
      HF_DATASETS_DISABLE_PROGRESS_BARS: "True"
      TQDM_DISABLE: "True"
      EVALUATE_VERBOSITY: "error"
      DATASETS_VERBOSITY: "error"
    deploy:
      replicas: 5
    extra_hosts:
      host.docker.internal: host-gateway
    volumes:
      - $SAMPLER_CONFIG_FILE:/home/app/configs/config.json
    networks:
     - testbench
     #- postgresql
     #- temporal
     #- mongodb

  requester:
    image: registry.digitalocean.com/poktscan/pocket_ml_testbench_requester:dev
    pull_policy: always
    container_name: requester
    environment:
      CONFIG_PATH: /home/app/configs/config.json
    extra_hosts:
      host.docker.internal: host-gateway
    volumes:
      - $REQUESTER_CONFIG_FILE:/home/app/configs/config.json
    networks:
      - testbench
      #- temporal
      #- mongodb
      - morse-localnet

  evaluator:
    image: registry.digitalocean.com/poktscan/pocket_ml_testbench_evaluator:dev
    pull_policy: always
    environment:
      CONFIG_PATH: /home/app/configs/config.json
      OPENAI_API_KEY: EMPTY
      HF_DATASETS_TRUST_REMOTE_CODE: "True"
      DATASETS_TRUST_REMOTE_CODE: "True"
      HF_DATASETS_DISABLE_PROGRESS_BARS: "True"
      TQDM_DISABLE: "True"
      EVALUATE_VERBOSITY: "error"
      DATASETS_VERBOSITY: "error"
    deploy:
      replicas: 5
    extra_hosts:
      host.docker.internal: host-gateway
    volumes:
      - $EVALUATOR_CONFIG_FILE:/home/app/configs/config.json
    networks:
      - testbench
      #- postgresql
      #- temporal
      #- mongodb

#  test-api:
#    image: registry.digitalocean.com/poktscan/pocket_ml_api:dev
#    pull_policy: always
#    environment:
#      MONGODB_URI: $MONGODB_URI
#    extra_hosts:
#      host.docker.internal: host-gateway
#    ports:
#      - 3001:3001

networks:
  testbench:
    name: testbench
    external: true
  #postgresql:
  #  name: postgresql
  #  external: true
  #mongodb:
  #  name: mongodb
  #  external: true
  morse-localnet:
    name: morse-localnet
    external: true