limit.maxIDLength:
  - value: 255
    constraints: {}
system.forceSearchAttributesCacheRefreshOnRead:
  - value: true # Dev setup only. Please don't turn this on in production.
    constraints: {}
# Total per-Namespace RPC rate limit applied across the Cluster.
frontend.rps:
  - value: 1000
# Total per-Namespace RPC rate limit applied across the Cluster.
frontend.namespaceRPS:
  - value: 1000
# Total per-Namespace RPC rate limit applied across the Cluster.
frontend.globalNamespaceRPS:
  - value: 1000
matching.rps:
  - value: 1000
matching.numTaskqueueReadPartitions:
  - value: 8
matching.numTaskqueueWritePartitions:
  - value: 8
  