limit.maxIDLength:
  - value: 255
    constraints: {}
system.forceSearchAttributesCacheRefreshOnRead:
  - value: true # Dev setup only. Please don't turn this on in production.
    constraints: {}
# Total per-Namespace RPC rate limit applied across the Cluster.
frontend.rps:
  - value: 10000
# Total per-Namespace RPC rate limit applied across the Cluster.
frontend.namespaceRPS:
  - value: 10000
# Total per-Namespace RPC rate limit applied across the Cluster.
frontend.globalNamespaceRPS:
  - value: 10000
matching.rps:
  - value: 10000
matching.numTaskqueueReadPartitions:
  - value: 16
matching.numTaskqueueWritePartitions:
  - value: 16
  