import type {Metadata} from 'next'
import {AppRouterCacheProvider} from '@mui/material-nextjs/v14-appRouter'
import React from 'react'
import ThemeProvider from '@/app/theme'
import CssBaseline from '@mui/material/CssBaseline'
import {cookies} from 'next/headers'
import AppBar from '@/app/AppBar/AppBar'
import ReactQueryProvider from '@/app/query'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <head>
      <title>PNYX</title>
      <link rel="shortcut icon" href={'/img/brand/favicon-32x32.png'}/>
      <link rel="apple-touch-icon" sizes="76x76" href={'/img/brand/apple-touch-icon.png'}/>
    </head>
    <body>
    <ReactQueryProvider>
      <AppRouterCacheProvider>
        <ThemeProvider defaultTheme={cookies().get('theme')?.value || 'dark'}>
          <CssBaseline enableColorScheme/>
          <AppBar/>
          {children}
        </ThemeProvider>
      </AppRouterCacheProvider>
    </ReactQueryProvider>
    </body>
    </html>
  )
}
