kind: Secret
apiVersion: v1
metadata:
  name: manager-config
type: Opaque
stringData:
  config.json: |
    {
      "mongodb_uri": "mongodb://mongodb-service:27017/pocket-ml-testbench?replicaSet=devRs&maxPoolSize=500&minPoolSize=50&w=1&readConcern=available&retryWrites=false&journal=false&connectTimeoutMS=5000&socketTimeoutMS=30000",
      "pocket_apps": $APPS_LIST,
      "pocket_rpc_url": "$POKT_RPC",
      "pocket_grpc_config": {
          "host_port": "$POKT_GRPC",
          "insecure": $POKT_GRPC_INSECURE
        },
      "pocket_blocks_per_session" : 10,
      "log_level": "debug",
      "develop": {
        "do_not_remove_tasks_from_db" : false
      },
      "temporal": {
        "host": "temporal-service",
        "port": 7233,
        "namespace": "pocket-ml-testbench",
        "task_queue": "manager",
        "worker": {
          "identity": "manager",
          "enable_logging_in_replay": false,
          "max_concurrent_activity_task_pollers": 80,
          "max_concurrent_workflow_task_pollers": 20,
          "deadlock_detection_timeout": 240
        },
        "sampler": {
          "workflow_name": "Sampler",
          "task_queue": "sampler"
        }
      },
      "frameworks": {
        "lmeh" : {
          "task_types": {"any" : "numerical"},
          "task_dependency": {"any" : ["signatures:tokenizer:ok", "signatures:config:ok"]},
          "schedule_limits": {"any" : "none:none"},
          "trigger_minimum": {"any" : "0"}
        },
        "lmeh-generative" : {
          "task_types": {"any" : "numerical"},
          "task_dependency": {"any" : ["none:none:none"]},
          "schedule_limits": {"any" : "none:none"},
          "trigger_minimum": {"any" : "0"}
        },
        "helm" : {
          "task_types": {"any" : "numerical"},
          "task_dependency": {"any" : ["signatures:tokenizer:ok", "signatures:config:ok"]},
          "schedule_limits": {"any" : "none:none"},
          "trigger_minimum": {"any" : "0"}
        },
        "signatures" : {
          "task_types": {"any" : "signature"},
          "task_dependency": {"any" : ["none:none:none"]},
          "schedule_limits": {"any" : "1:session"},
          "trigger_minimum": {"tokenizer" : "1", "config" : "1"}
        }
      },
      "external_suppliers" : $EXT_SUPPLIERS_TRACK
    }
