kind: Secret
apiVersion: v1
metadata:
  name: requester-config
type: Opaque
stringData:
  config.json: |
    {
      "mongodb_uri": "mongodb://mongodb-service:27017/pocket-ml-testbench?replicaSet=devRs&maxPoolSize=500&minPoolSize=50&w=1&readConcern=available&retryWrites=false&journal=false&connectTimeoutMS=5000&socketTimeoutMS=30000",
      "pocket_apps": $APPS_LIST,
      "pocket_rpc_url": "$POKT_RPC",
      "pocket_grpc_config": {
          "host_port": "$POKT_GRPC",
          "insecure": true
        },
      "pocket_blocks_per_session" : 10,
      "relay": {
        "time_between_relays" : 0.1,
        "time_dispersion" : 0.05,
        "retries": 1,
        "min_backoff": 10,
        "max_backoff": 60,
        "req_per_sec": 10,
        "session_tolerance": 1
      },
      "log_level": "debug",
      "temporal": {
        "host": "temporal-service",
        "port": 7233,
        "namespace": "pocket-ml-testbench",
        "task_queue": "requester",
        "worker": {
          "identity": "requester",
          "enable_logging_in_replay": false,
          "max_concurrent_activity_task_pollers": 2500,
          "deadlock_detection_timeout": 120,
          "worker_activities_per_second": 500
        },
        "evaluator": {
          "workflow_name": "Evaluator",
          "task_queue": "evaluator"
        }
      }
    }