kind: Secret
apiVersion: v1
metadata:
  name: requester-config
type: Opaque
stringData:
  config.json: |
    {
      "mongodb_uri": "mongodb://mongodb-service:27017/pocket-ml-testbench?replicaSet=devRs&maxPoolSize=500&minPoolSize=50&w=1&readConcern=available&retryWrites=false&journal=false&connectTimeoutMS=5000&socketTimeoutMS=30000",
      "apps": $APPS_PRIVATE_KEYS_LIST,
      "rpc": {
        "urls": $POKT_RPC_LIST,
        "retries": 1,
        "min_backoff": 10,
        "max_backoff": 60,
        "req_per_sec": 3,
        "session_tolerance": 1
      },
      "relay": {
        "time_between_relays" : 3,
        "time_dispersion" : 0.25
      },
      "log_level": "info",
      "temporal": {
        "host": "temporal",
        "port": 7233,
        "namespace": "pocket-ml-testbench",
        "task_queue": "requester",
        "worker": {
          "identity": "requester",
          "enable_logging_in_replay": false,
          "max_concurrent_activity_task_pollers": 2500,
          "deadlock_detection_timeout": 120,
          "worker_activities_per_second": 500
        },
        "evaluator": {
          "workflow_name": "Evaluator",
          "task_queue": "evaluator"
        }
      }
    }