apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  labels:
    app: postgresql
stringData:
  POSTGRES_USER: testbench
  POSTGRES_PASSWORD: 5iR500QPdHJs9YocKOeSq5DFgevgaQiAWXEtPOtjWsjKrnUFs8
  POSTGRES_DB: pocket-ml-testbench
  POSTGRES_PORT: "5432"
  POSTGRES_SEEDS: postgresql